import { expect } from "chai";
import { ethers } from "hardhat";
import { StandardMerkleTree } from "@openzeppelin/merkle-tree";

/**
 * 🔴 **Cross-repository fixed vector.** Generated by the platform's off-chain
 *    Merkle implementation; both repositories pin the same bytes, so if either
 *    side changes how the tree is built, this turns red immediately.
 *    Testing only one side is the same as not testing: two implementations that
 *    are each internally consistent but compute different roots is the one fatal
 *    failure mode of this design — and a root, once on chain, can never be changed.
 */
const VECTOR = {
  root: "0xa321124972cadb93cbe692c5cd0ed54310499470df753ce80b39459d05d6466c",
  totalAmount: 123457089012387n,
  count: 5,
  entries: [
    { account: "0x1375b29a88474199E1AA5b46C639D0c3cDf5EAfB", amount: 1n,
      proof: ["0xfb33f6ba16ebcd4a8525738654500878471bb4b2ed45d070d04edf3c1863b412",
              "0xb5eff6f93f5bebab167fca886b192df1230d30e717025220885678fa83c0561f"] },
    { account: "0x312e1DC164FaA89212DEb9d5b2635BB4abcA8a12", amount: 199999999n,
      proof: ["0xb0b4db41faf1d4b934e6599702eef08dab0842847621a031defc4d64a4c67a9b",
              "0xd3c41cb17a2e9c1e2ad639ec8daf58334f0a0e00a2bbc83493a80b7870ab3faf"] },
    { account: "0x31567650f1d7672358B1265FCd95d36A7c7A0825", amount: 100000000n,
      proof: ["0x47717102109e8bbd817082d7ee74b639c80cb813a12f974282b9725954f13a9a",
              "0xcd9cfdf3a328637f5af6c713c372427b0fa9419b8f783b1bd3a5a394adc88269",
              "0xb5eff6f93f5bebab167fca886b192df1230d30e717025220885678fa83c0561f"] },
    { account: "0x76371918bc75470CEE749685dC57bd6c3B8e82f2", amount: 42n,
      proof: ["0xa372c07455cf738a13e78fda38ee1a138a12693beaf86bbf5aef5c0fb176cbdf",
              "0xd3c41cb17a2e9c1e2ad639ec8daf58334f0a0e00a2bbc83493a80b7870ab3faf"] },
    { account: "0xD8618C1CCDB57606bfCEc1E7dE09402B8e64A25A", amount: 123456789012345n,
      proof: ["0x18f6e0f3ece89168dd7a7b01ebf615d1693c1586a7604dc43b22f9d74c087525",
              "0xcd9cfdf3a328637f5af6c713c372427b0fa9419b8f783b1bd3a5a394adc88269",
              "0xb5eff6f93f5bebab167fca886b192df1230d30e717025220885678fa83c0561f"] },
  ],
};

describe("PayoutRootRegistry", () => {
  async function setup() {
    const [owner, outsider] = await ethers.getSigners();
    const Reg = await ethers.getContractFactory("PayoutRootRegistry");
    const reg = await Reg.deploy(owner.address);
    await reg.waitForDeployment();
    const Checker = await ethers.getContractFactory("MerkleProofChecker");
    const checker = await Checker.deploy();
    await checker.waitForDeployment();
    return { owner, outsider, reg, checker };
  }

  describe("publishing", () => {
    it("is readable once published, and the event carries periodId / root / total / count", async () => {
      const { reg } = await setup();
      await expect(reg.publishRoot(42n, VECTOR.root, VECTOR.totalAmount, VECTOR.count))
        .to.emit(reg, "RootPublished")
        .withArgs(42n, VECTOR.root, VECTOR.totalAmount, VECTOR.count);

      const p = await reg.periods(42n);
      expect(p.root).to.equal(VECTOR.root);
      expect(p.totalAmount).to.equal(VECTOR.totalAmount);
      expect(p.count).to.equal(VECTOR.count);
      expect(p.publishedAt).to.be.greaterThan(0n);
      expect(await reg.isPublished(42n)).to.equal(true);
    });

    it("🔴 a period can only be published once — a root that can be overwritten is not a commitment", async () => {
      const { reg } = await setup();
      await reg.publishRoot(1n, VECTOR.root, 100n, 1);
      const other = "0x" + "11".repeat(32);
      await expect(reg.publishRoot(1n, other, 100n, 1)).to.be.revertedWith("Already published");
      // republishing the same root is rejected too: an off-chain retry should read
      // isPublished first rather than firing blindly
      await expect(reg.publishRoot(1n, VECTOR.root, 100n, 1)).to.be.revertedWith("Already published");
      expect((await reg.periods(1n)).root).to.equal(VECTOR.root);
    });

    it("periods do not interfere with one another", async () => {
      const { reg } = await setup();
      const a = "0x" + "aa".repeat(32);
      const b = "0x" + "bb".repeat(32);
      await reg.publishRoot(1n, a, 10n, 1);
      await reg.publishRoot(2n, b, 20n, 2);
      expect((await reg.periods(1n)).root).to.equal(a);
      expect((await reg.periods(2n)).root).to.equal(b);
    });

    it("an unpublished period reads back as all zeroes, with isPublished false", async () => {
      const { reg } = await setup();
      const p = await reg.periods(999n);
      expect(p.root).to.equal(ethers.ZeroHash);
      expect(await reg.isPublished(999n)).to.equal(false);
    });

    it("an empty root / an empty list / a zero total are all rejected rather than silently stored", async () => {
      const { reg } = await setup();
      await expect(reg.publishRoot(1n, ethers.ZeroHash, 1n, 1)).to.be.revertedWith("Empty root");
      await expect(reg.publishRoot(1n, VECTOR.root, 1n, 0)).to.be.revertedWith("Empty period");
      await expect(reg.publishRoot(1n, VECTOR.root, 0n, 1)).to.be.revertedWith("Zero total");
    });

    it("only the owner can publish", async () => {
      const { reg, outsider } = await setup();
      await expect(reg.connect(outsider).publishRoot(1n, VECTOR.root, 1n, 1))
        .to.be.revertedWithCustomError(reg, "OwnableUnauthorizedAccount");
    });
  });

  describe("🔴 byte-for-byte agreement with the off-chain implementation (cross-repository vector)", () => {
    it("every proof generated off chain is accepted by the real Solidity MerkleProof.verify", async () => {
      const { checker } = await setup();
      for (const e of VECTOR.entries) {
        expect(
          await checker.verify(e.proof, VECTOR.root, e.account, e.amount),
          `proof for ${e.account} was rejected`,
        ).to.equal(true);
      }
    });

    it("changing the amount by one base unit fails verification — the root commits to the (address, amount) pair", async () => {
      const { checker } = await setup();
      const e = VECTOR.entries[1]!;
      expect(await checker.verify(e.proof, VECTOR.root, e.account, e.amount + 1n)).to.equal(false);
      expect(await checker.verify(e.proof, VECTOR.root, e.account, e.amount - 1n)).to.equal(false);
    });

    it("someone else\u0027s proof does not verify against your own address", async () => {
      const { checker } = await setup();
      const a = VECTOR.entries[0]!, b = VECTOR.entries[3]!;
      expect(await checker.verify(a.proof, VECTOR.root, b.account, b.amount)).to.equal(false);
    });

    it("leaf encoding is byte-for-byte identical to the OpenZeppelin merkle-tree library", async () => {
      const { checker } = await setup();
      const e = VECTOR.entries[2]!;
      const oz = StandardMerkleTree.of([[e.account, e.amount.toString()]], ["address", "uint256"]);
      expect((await checker.leafOf(e.account, e.amount)).toLowerCase())
        .to.equal(oz.leafHash([e.account, e.amount.toString()]).toLowerCase());
    });

    it("rebuilding this list with the OpenZeppelin library reproduces the vector\u0027s root", async () => {
      const oz = StandardMerkleTree.of(
        VECTOR.entries.map((e) => [e.account, e.amount.toString()]),
        ["address", "uint256"],
      );
      expect(oz.root.toLowerCase()).to.equal(VECTOR.root.toLowerCase());
    });

    it("the vector\u0027s total and count are self-consistent", () => {
      expect(VECTOR.entries.reduce((s, e) => s + e.amount, 0n)).to.equal(VECTOR.totalAmount);
      expect(VECTOR.entries.length).to.equal(VECTOR.count);
    });
  });

  describe("gas", () => {
    it("publishing one period costs about 70,000 gas", async () => {
      const { reg } = await setup();
      const tx = await reg.publishRoot(7n, VECTOR.root, VECTOR.totalAmount, VECTOR.count);
      const r = await tx.wait();
      console.log(`      measured ${r!.gasUsed} gas`);
      // the struct packs into 2 slots; exceeding this means the packing was broken
      // (for example by widening totalAmount back to uint256)
      expect(r!.gasUsed).to.be.lessThan(80_000n);
    });
  });
});
